---
- hosts: kube-master
  gather_facts: false
  tasks:
  - name: shutdown VM
    delegate_to: "{{ virt_host }}"
    virt:
      name: "{{ inventory_hostname }}"
      state: destroyed
      uri: "{{ hostvars[virt_host].virt_uri }}"
  - name: undefine VM
    delegate_to: "{{ virt_host }}"
    virt:
      name: "{{ inventory_hostname }}"
      command: undefine
      uri: "{{ hostvars[virt_host].virt_uri }}"
  - name: remove snapshot
    delegate_to: "{{ virt_host }}"
    file:
      path: "{{ hostvars[virt_host].virt_images }}/{{ inventory_hostname }}.qcow2"
      state: absent
  - name: remove ignition config
    delegate_to: "{{ virt_host }}"
    file:
      path: "{{ hostvars[virt_host].virt_images }}/{{ inventory_hostname }}.ign"
      state: absent
  - name: remove SSH hostkeys backup file
    delegate_to: "{{ virt_host }}"
    run_once: true
    file:
      path: "{{ lookup('env','HOME') }}/.ssh/known_hosts.old"
      state: absent
  - name: remove SSH host key from cache
    delegate_to: "{{ virt_host }}"
    known_hosts:
      name: "{{ item }}"
      state: absent
    with_items:
    - "{{ inventory_hostname }}"
    - "{{ ansible_host }}"
...
