---
- name: 'Install NFS Client Provisioner (sc {{ item.name }})'
  include_role:
    name: helmchart
  vars:
    helm:
      release_name: 'nfs-{{ item.name }}'
      namespace: nfs
      chart: stable/nfs-client-provisioner
      values_template: nfs-values.yaml.j2
    share:
      class: 'nfs-{{ item.name }}'
      server: '{{ item.server }}'
      path: '{{ item.path }}'
      default: '{{ item.default }}'
  with_items: '{{ nfs_shares }}'

- name: Install Traefik
  include_role:
    name: helmchart
  vars:
    helm:
      release_name: traefik
      namespace: traefik
      chart: stable/traefik
      values_template: traefik-values.yaml.j2

- name: Install Heapster
  include_role:
    name: helmchart
  vars:
    helm:
      release_name: heapster
      namespace: kube-system
      chart: stable/heapster
      values_template: heapster-values.yaml.j2

- name: Fix Kubernetes Dashboard
  include_tasks: dashboard.yaml
...
