---
- name: Install Traefik
  include_role:
    name: helmchart
  vars:
    helm:
      release_name: traefik
      namespace: traefik
      chart: stable/traefik
      values_template: traefik-values.yaml.j2

- name: Fix Kubernetes Dashboard
  include_tasks: dashboard.yaml
...
