---
- name: 'Install NFS Client Provisioner (sata)'
  include_role:
    name: helmchart
  vars:
    helm:
      release_name: 'nfs-sata'
      namespace: nfs
      src:
        type: chart
        chart: stable/nfs-client-provisioner
      values:
        nfs:
          server: '{{ nfs_sata_server }}'
          path: '{{ nfs_sata_share }}'
        storageClass:
          name: sata
          defaultClass: true
          archiveOnDelete: false
        resources:
          requests:
            cpu: 50m

- name: 'Install NFS Client Provisioner (ssd)'
  include_role:
    name: helmchart
  vars:
    helm:
      release_name: 'nfs-ssd'
      namespace: nfs
      src:
        type: chart
        chart: stable/nfs-client-provisioner
      values:
        nfs:
          server: '{{ nfs_ssd_server }}'
          path: '{{ nfs_ssd_share }}'
        storageClass:
          name: ssd
          defaultClass: false
          archiveOnDelete: false
        resources:
          requests:
            cpu: 50m

- name: 'Install Traefik'
  include_role:
    name: helmchart
  vars:
    helm:
      release_name: traefik
      namespace: traefik
      src:
        type: chart
        chart: stable/traefik
      values:
        serviceType: NodePort
        service:
          nodePorts:
            http: 30080
            https: 30443
        acme:
          challengeType: http-01
          enabled: true
          email: '{{ traefik_acme_email }}'
          staging: false
          logging: true
        cpuRequest: 50m
        dashboard:
          enabled: true
          domain: '{{ traefik_dashboard_domain }}'
        rbac:
          enabled: true
        ssl:
          enabled: true
          insecureSkipVerify: true

- name: 'Install Heapster'
  include_role:
    name: helmchart
  vars:
    helm:
      release_name: heapster
      namespace: kube-system
      src:
        type: chart
        chart: stable/heapster
      values:
        resources:
          requests:
            cpu: 50m

- name: Install Nextcloud
  include_role:
    name: helmchart
  vars:
    helm:
      src:
        type: git
        remote: https://github.com/jonkerj/chart-nextcloud.git
        version: master
      values:
        nextcloudUsername: jorik
        nextcloudPassword: frop
        nextcloudEmail: jorik@kippendief.biz
        nextcloudHost: nc.k8s.efgh.nl
        serviceType: ClusterIP
        ingress: 
          enabled: true
        resources:
          requests:
            cpu: 50m
      namespace: nextcloud
      release_name: nextcloud

- name: Fix Kubernetes Dashboard
  include_tasks: dashboard.yaml
...
