---
- name: Install NFS Client Provisioner
  include_role:
    name: helmchart
  vars:
    helm:
      release_name: nfs
      namespace: nfs
      chart: stable/nfs-client-provisioner
      values_template: nfs-values.yaml.j2

- name: Install Traefik
  include_role:
    name: helmchart
  vars:
    helm:
      release_name: traefik
      namespace: traefik
      chart: stable/traefik
      values_template: traefik-values.yaml.j2

- name: Install Heapster
  include_role:
    name: helmchart
  vars:
    helm:
      release_name: heapster
      namespace: kube-system
      chart: stable/heapster

- name: Fix Kubernetes Dashboard
  include_tasks: dashboard.yaml
...
