---
- name: Install Helm Chart {{ item.release_name }}
  include_role:
    name: helmchart
  vars:
    helm: '{{ item }}'
  with_items: '{{ helm_charts }}'

- name: Fix Kubernetes Dashboard
  include_tasks: dashboard.yaml
...
