---
- name: Check Traefik install
  command: 'helm list ^traefik$'
  register: helmlist

- name: Template values.yaml
  template:
    src: traefik-values.yaml.j2
    dest: "{{ populate_tempdir.path }}/traefik-values.yaml"
  when: '"traefik" not in helmlist.stdout'

- name: Install Traefik helm chart
  command: "helm install -f {{ populate_tempdir.path }}/traefik-values.yaml --namespace traefik -n traefik stable/traefik"
  when: '"traefik" not in helmlist.stdout'
...
