---
all:
  hosts:
    localhost:
    master1:
      ansible_host: 172.21.46.8
      mac: 06:e2:11:7f:cf:01
      vmid: 151
    master2:
      ansible_host: 172.21.46.9
      mac: 06:e2:11:7f:cf:02
      vmid: 152
    master3:
      ansible_host: 172.21.46.10
      mac: 06:e2:11:7f:cf:03
      vmid: 153
    worker1:
      ansible_host: 172.21.46.11
      mac: 06:e2:11:7f:cf:04
      vmid: 154
    worker2:
      ansible_host: 172.21.46.12
      mac: 06:e2:11:7f:cf:05
      vmid: 155
    worker3:
      ansible_host: 172.21.46.13
      mac: 06:e2:11:7f:cf:06
      vmid: 156
  children:
    k8s-cluster:
      children:
        kube-master:
          hosts:
            master1:
            master2:
            master3:
        kube-node:
          hosts:
            worker1:
            worker2:
            worker3:
    etcd:
      hosts:
        master1:
        master2:
        master3:
...
