---
all:
  hosts:
    localhost:
    kube1:
      ansible_host: 172.21.46.8
      mac: 06:e2:11:7f:cf:01
      vmid: 151
    kube2:
      ansible_host: 172.21.46.9
      mac: 06:e2:11:7f:cf:02
      vmid: 152
    kube3:
      ansible_host: 172.21.46.10
      mac: 06:e2:11:7f:cf:03
      vmid: 153
  children:
    k8s-cluster:
      children:
        kube-master:
          hosts:
            kube1:
            kube2:
            kube3:
        kube-node:
          hosts:
            kube1:
            kube2:
            kube3:
    etcd:
      hosts:
        kube1:
        kube2:
        kube3:
...
