---
all:
  hosts:
    localhost:
    kube1:
      ansible_host: 172.21.45.2
  children:
    k8s-cluster:
      children:
        kube-master:
          hosts:
            kube1:
        kube-node:
          hosts:
            kube1:
    etcd:
      hosts:
        kube1:
...
