---
apiserver_loadbalancer_domain_name: "k8s.efgh.nl"
calico_node_cpu_requests: 150m
dns_cpu_requests: 150m
helm_values_dir: '{{ inventory_dir }}/../helm-values'
helm_charts:
- name: 'NFS Client Provisioner (ssd)'
  release_name: 'nfs-ssd'
  namespace: nfs
  src:
    type: chart
    chart: stable/nfs-client-provisioner
  values:
    nfs:
      server: '{{ nfs_ssd_server }}'
      path: '{{ nfs_ssd_share }}'
    storageClass:
      name: ssd
      defaultClass: true
      archiveOnDelete: false
- name: 'NFS Client Provisioner (sas)'
  release_name: 'nfs-sas'
  namespace: nfs
  src:
    type: chart
    chart: stable/nfs-client-provisioner
  values:
    nfs:
      server: '{{ nfs_sas_server }}'
      path: '{{ nfs_sas_share }}'
    storageClass:
      name: sas
      defaultClass: false
      archiveOnDelete: false
- name: 'Traefik'
  release_name: traefik
  namespace: traefik
  src:
    type: chart
    chart: stable/traefik
  values:
    serviceType: NodePort
    service:
      nodePorts:
        http: 30080
        https: 30443
    acme:
      challengeType: http-01
      enabled: true
      email: '{{ traefik_acme_email }}'
      staging: false
      logging: true
    dashboard:
      enabled: true
      domain: '{{ traefik_dashboard_domain }}'
    proxyProtocol:
      enabled: true
      trustedIPs:
      - 172.21.46.1
    rbac:
      enabled: true
    ssl:
      enabled: true
      insecureSkipVerify: true
    resources:
      requests:
        cpu: 125m
        memory: 100Mi
      limits:
        cpu: 500m
        memory: 500Mi
- name: 'Heapster'
  release_name: heapster
  namespace: kube-system
  src:
    type: chart
    chart: stable/heapster
  values:
- name: 'Nextcloud'
  release_name: nextcloud
  namespace: nextcloud
  src:
    type: git
    remote: https://github.com/jonkerj/chart-nextcloud.git
    version: master
  values:
    nextcloudUsername: admin
    nextcloudEmail: jorik@kippendief.biz
    nextcloudHost: nc.k8s.efgh.nl
    serviceType: ClusterIP
    ingress: 
      enabled: true
kube_proxy_cpu_requests: 150m
kube_read_only_port: 10255
loadbalancer_apiserver:
  address: 185.76.17.60
  port: 6443
nfs_ssd_server: 172.21.46.2
nfs_ssd_share: /ssd/k8s
nfs_sas_server: 172.21.46.2
nfs_sas_share: /rpool/k8s
traefik_dashboard_domain: traefik.k8s.efgh.nl
traefik_acme_email: jorik@kippendief.biz
...
