---
apiserver_loadbalancer_domain_name: "k8s.efgh.nl"
calico_node_cpu_requests: 50m
dns_cpu_requests: 50m
dns_min_replicas: 1
helm_values_dir: '{{ inventory_dir }}/../helm-values'
kube_proxy_cpu_requests: 50m
kube_read_only_port: 10255
loadbalancer_apiserver:
  address: 185.76.17.60
  port: 6443
nfs_sata_server: 172.21.45.1
nfs_sata_share: /srv/k8s-sata
nfs_ssd_server: 172.21.45.1
nfs_ssd_share: /srv/k8s-ssd
traefik_dashboard_domain: traefik.k8s.efgh.nl
traefik_acme_email: jorik@kippendief.biz
...
