---
ansible_become: true
ansible_python_interpreter: /opt/bin/python
ansible_user: core
bin_dir: /opt/bin
coreos_image_url: https://stable.release.core-os.net/amd64-usr/current/coreos_production_qemu_image.img.bz2
etcd_data_dir: /var/lib/etcd
helm_enabled: true
kube_base_image: kube-base
kube_bridge: br0
kube_gateway: 172.21.45.1
kube_memory_gb: 4
kube_prefix_length: 24
kube_proxy_mode: iptables
kube_ssh_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCUBx6AbKzsV/gc2q/F9c7yrvb12tnC9xQ1ugp+9cTGCrt0YEM+DYBfcRXE8964Tk47Dj4qTQeHpCJCe8IaFkellX6NAiiUx2esE9noJJjh6X+D30DRN9gwt0fUMH1ig6X3zE5fISqxLv1kEbaa33E4e28LH7Uz5cjAPRmfHqmF5ghfWDNPi/iSkD+N0quG69PH7XL9WjegGDaJPxnao2bNMozQeer9c/oAQElZOz4MDR3YjpFWwIiMgaOL/y0hIf4JjDkwOlY1uYGlt4AL11N9/3+TqWsoyhbyJ7BLBkDB8rKKcdkGf68+oawcStyWYRaz+t6+atFUeMaiPiyFwjfZ jorik@carbon
kube_vcpu: 2
resolvconf_mode: host_resolvconf
upstream_dns_servers:
- 87.249.121.121
- 77.222.77.222
virt_host: localhost
...
