---
ansible_become: true
ansible_python_interpreter: /opt/bin/python
ansible_user: core
bin_dir: /opt/bin
coreos_image_url: https://stable.release.core-os.net/amd64-usr/current/coreos_production_qemu_image.img.bz2
etcd_data_dir: /var/lib/etcd
helm_enabled: true
kube_network_plugin: weave
kube_proxy_mode: iptables
resolvconf_mode: host_resolvconf
upstream_dns_servers:
- 87.249.121.121
- 77.222.77.222
virt_base_image: kube-base
virt_bridge: br0
virt_vcpu: 2
virt_gateway: 172.21.45.1
virt_host: localhost
virt_memory_gb: 4
virt_prefix_length: 24
virt_ssh_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCUBx6AbKzsV/gc2q/F9c7yrvb12tnC9xQ1ugp+9cTGCrt0YEM+DYBfcRXE8964Tk47Dj4qTQeHpCJCe8IaFkellX6NAiiUx2esE9noJJjh6X+D30DRN9gwt0fUMH1ig6X3zE5fISqxLv1kEbaa33E4e28LH7Uz5cjAPRmfHqmF5ghfWDNPi/iSkD+N0quG69PH7XL9WjegGDaJPxnao2bNMozQeer9c/oAQElZOz4MDR3YjpFWwIiMgaOL/y0hIf4JjDkwOlY1uYGlt4AL11N9/3+TqWsoyhbyJ7BLBkDB8rKKcdkGf68+oawcStyWYRaz+t6+atFUeMaiPiyFwjfZ jorik@carbon
...
