---
ansible_become: true
ansible_python_interpreter: /opt/bin/python
ansible_user: core
bin_dir: /opt/bin
coreos_ignition:
  storage:
    files:
    - path: "/etc/hostname"
      filesystem: "root"
      contents:
        inline: '{{ inventory_hostname }}'
  passwd:
    users:
    - name: "core"
      ssh_authorized_keys:
      - '{{ virt_ssh_key }}'
  networkd:
    units:
    - name: 00-eth0.network
      contents: |
        [Match]
        Name=eth0

        [Network]
        DNS=77.222.77.222
        DNS=87.249.121.121
        Address={{ ansible_host }}/{{ virt_prefix_length }}
        Gateway={{ virt_gateway }}
coreos_version: 1967.4.0
etcd_data_dir: /var/lib/etcd
helm_enabled: true
kube_network_plugin: calico
kube_proxy_mode: iptables
pve:
  user: root@pam
  host: pve.efgh.nl:443
  password: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    37623461333632363330363364653438353664343361343365666230383631656437623838313562
    6562623931373661343039373134653137613663646162630a626438343763613034336334663361
    63616662323362626136323162313933356636666335373864643137633438306661383164306466
    6363303138313631650a663731346238353834333332336634373566663436346637656631653834
    6238
  node: pve
  hw:
    bridge: vmbr0
    storage: ssd
    memory: 4096
    sockets: 2
    cores: 1
resolvconf_mode: host_resolvconf
upstream_dns_servers:
- 172.21.46.1
virt_base_image: kube-base
virt_bridge: br0
virt_vcpu: 2
virt_gateway: 172.21.46.1
virt_host: localhost
virt_memory_gb: 8
virt_prefix_length: 24
virt_ssh_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCUBx6AbKzsV/gc2q/F9c7yrvb12tnC9xQ1ugp+9cTGCrt0YEM+DYBfcRXE8964Tk47Dj4qTQeHpCJCe8IaFkellX6NAiiUx2esE9noJJjh6X+D30DRN9gwt0fUMH1ig6X3zE5fISqxLv1kEbaa33E4e28LH7Uz5cjAPRmfHqmF5ghfWDNPi/iSkD+N0quG69PH7XL9WjegGDaJPxnao2bNMozQeer9c/oAQElZOz4MDR3YjpFWwIiMgaOL/y0hIf4JjDkwOlY1uYGlt4AL11N9/3+TqWsoyhbyJ7BLBkDB8rKKcdkGf68+oawcStyWYRaz+t6+atFUeMaiPiyFwjfZ jorik@carbon
...
