storage:
  files:
  - path: "/etc/hostname"
    filesystem: "root"
    contents:
      inline: {{ inventory_hostname }}
passwd:
  users:
  - name: "core"
    ssh_authorized_keys:
    - {{ kube_ssh_key }}
networkd:
  units:
  - name: 00-eth0.network
    contents: |
      [Match]
      Name=eth0

      [Network]
      DNS=77.222.77.222
      DNS=87.249.121.121
      Address={{ ansible_host }}/{{ kube_prefix_length }}
      Gateway={{ kube_gateway }}
